### ISSUE TITLE
Cannot assign to non-existent property filterVirtualDevices

### ISSUE THREAD

**Issue by Slothinger** [denilsonsa/plasma-audio-device-switcher#1]
On Kubuntu (22.04) i get the following error message with version 1.0.

`file:///home/username/.local/share/plasma/plasmoids/org.kde.plasma.audiodeviceswitcher-ng/contents/ui/main.qml:57:9: Cannot assign to non-existent property "filterVirtualDevices"`

Tried it with the current kde neon release and got it working without this error. 
Any ideas?

**Comment by jkhunter** [comment]
your plasma pulse audio version is to old. This attribute was introduced in Mar 30, 2022

https://github.com/KDE/plasma-pa/commit/d915cbd613aa6b0bc5bc181ae93a96f110e6a64c#diff-6a18964d36d154dc7dcb6b3d346dc27976e3d885938fbe69d0453f7319d9319b
